spring:
  application:
    name: cloud-application
  data:
    mongodb:
      uri: mongodb+srv://bullyrooks:${mongodb.password}@bullyrooks.4zqpz.mongodb.net/bullyrooks?retryWrites=true&w=majority
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: readinessState,mongo,messageGeneratorHealth
          show-details: always
          status:
            order: down,out-of-service,unknown,up

#  health:
#    livenessstate:
#      enabled: true
#    readinessstate:
#      enabled: true
feign:
  client:
    config:
      healthClient:
        connectTimeout: 1000
        readTimeout: 1000