spring:
  application:
    name: cloud-application
  cloud:
    stream:
      function:
        bindings:
          messageEvent-out-0:
            destination: message.created
  kafka:
    properties:
      sasl.mechanism: PLAIN
      bootstrap.servers: pkc-2396y.us-east-1.aws.confluent.cloud:9092
      security.protocol: SASL_SSL
#      basic.auth.credentials.source: USER_INFO
#      schema.registry.basic.auth.user.info: {{ SR_API_KEY }}:{{ SR_API_SECRET }}
#      schema.registry.url: https://psrc-gk071.us-east-2.aws.confluent.cloud

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: "readinessState,messageGenerator"
    metrics:
      enabled: true

feign:
  client:
    config:
      healthClient:
        connectTimeout: 1000
        readTimeout: 1000

logging:
  level:
    root: INFO
    com.bullyrooks: DEBUG
    io.micrometer.logzio: WARN
logzio:
  metrics:
    url: https://listener.logz.io:8053
    registry:
      mock: false