kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cloud_application.fullname" . }}-reader-role
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]